name: 'Get Pull Request From SHA'
description: 'Get Pull Request From SHA'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  sha:
    required: false
    description: 'Commit SHA'
outputs:
  title:
    description: 'PR Title'
  body:
    description: 'PR Body'
  number:
    description: 'PR Number'
  labels:
    description: 'PR Labels'
runs:
  using: 'node12'
  main: 'dist/index.js'
